# Generated by Django 2.1.4 on 2018-12-18 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default=1, help_text='The Name of the Author', max_length=250),
        ),
        migrations.AlterField(
            model_name='todo',
            name='author',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='todoapp.Author'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='content',
            field=models.CharField(default=1, help_text='Your todo', max_length=1000),
        ),
    ]
